export const FETCH_STOCK_DATA = "FETCH_STOCK_DATA";
export const CREATE_STOCK_DATA = "CREATE_STOCK_DATA";
export const UPDATE_STOCK_DATA = "UPDATE_STOCK_DATA";
export const DELETE_STOCK_DATA = "DELETE_STOCK_DATA";
